# This is a basic workflow for building the README.md file

name: Daily Quote

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #  branches: [ master ]
  # pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  schedule:
    - cron:  '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
           python-version: 3.8
      - uses: actions/cache@v4
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
             ${{ runner.os }}-pip- 
      # Runs python pip command using the runners shell to install dependencies
      - name:  Install Python dependencies
        run: python -m pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: Generate random quote as a gif asset
        run: |
          python gengif.py

      - name: Commit and push if any changes
        run: |
          git diff
          git config --global user.email "trabdlkarim@zohomail.eu"
          git config --global user.name "trabdlkarim"
          git add -A
          git commit -m "generate profile inspirational quote via github-actions" || exit 0
          git push -u origin master
